site_name: NEXT – Guide & Référentiel
site_author: Alex Lamizana
site_description: Documentation pour NEXT

nav:
  - Accueil: index.md
  - Vue d'ensemble:
    - Architecture: vue-densemble/architecture.md
    - Principaux modules: vue-densemble/principaux-modules.md
  - Guide utilisateur:
    - Navigation générale: guide-utilisateur/navigation.md
    - Comptes utilisateurs:
      - Connexion et authentification: guide-utilisateur/comptes/connexion.md
      - Paramétrage du compte utilisateur: guide-utilisateur/comptes/parametre-utilisateur.md
    - Gestion des ventes:
      - Devis: guide-utilisateur/gestion-ventes/devis.md
      - Commandes: guide-utilisateur/gestion-ventes/commandes.md
      - Livraisons: guide-utilisateur/gestion-ventes/livraisons.md
      - Factures: guide-utilisateur/gestion-ventes/factures.md
      - Paiement: guide-utilisateur/gestion-ventes/paiement.md
      - Clients:
        - Fiches clients: guide-utilisateur/gestion-ventes/clients/fiche.md
        - Suivi commercial: guide-utilisateur/gestion-ventes/clients/suivi-commercial.md
        - Suivi comptable: guide-utilisateur/gestion-ventes/clients/suivi-comptable.md
      - Mise en pratique: guide-utilisateur/gestion-ventes/mise-en-pratique.md
    - Gestion des achats:
      - Demande d'achats: guide-utilisateur/gestion-achats/demande.md
      - Commandes d'achats: guide-utilisateur/gestion-achats/commande.md
      - Réceptions: guide-utilisateur/gestion-achats/receptions.md
      - Factures d'achats: guide-utilisateur/gestion-achats/factures.md
      - Fournisseurs: guide-utilisateur/gestion-achats/fournisseurs.md
    - Gestion des stocks:
      - Articles: guide-utilisateur/gestion-stocks/articles.md
      - Ajustements: guide-utilisateur/gestion-stocks/ajustements.md
      - Inventaires: guide-utilisateur/gestion-stocks/inventaires.md
      - Transferts intradépôt: guide-utilisateur/gestion-stocks/transferts.md
    - Mise en pratique: guide-utilisateur/pratique.md
  - Contact: contact.md
  - FAQ: faq.md
  - Terms: terms.md


theme:
  name: material                  # mkdocs,readthedocs
  custom_dir: overrides
  user_color_mode_toggle: true
  highlight.js: true
  shortcuts:
    help: 191    # ?
    next: 78     # n
    previous: 80 # p
    search: 83   # s
  features:                       # navbar lateral pour la navigation.
    - navigation.sections
  #   - navigation.tabs
  #   - navigation.instant
  #   - navigation.top

extra:
  version: 1.0.0
  copyright: NEXT

# extra_css:
#   - css/custom.css
