site_name: NEXT – Guide & Référentiel
site_author: Alex Lamizana
site_description: Documentation pour NEXT

nav:
  - Accueil: index.md
  - Vue d'ensemble:
    - Architecture: Architecture.md
    - Principaux modules: principaux-modules.md
  - Guide utilisateur:
    - Connexion et authentification: utilisateur/connexion.md
    - Paramétrage du compte utilisateur: utilisateur/parametre-utilisateur.md
    - Navigation générale: utilisateur/navigation.md
    - Gestion des ventes:
      - Devis: utilisateur/gestion-ventes/devis.md
      - Commandes: utilisateur/gestion-ventes/commandes.md
      - Livraisons: utilisateur/gestion-ventes/bon-de-livraisons.md
      - Factures: utilisateur/gestion-ventes/factures.md
      - Paiement: utilisateur/gestion-ventes/paiement.md
      - Clients:
        - Fiches clients: utilisateur/gestion-ventes/clients/fiches-clients.md
        - Suivi commercial: utilisateur/gestion-ventes/clients/suivi-commercial.md
        - Suivi comptable: utilisateur/gestion-ventes/clients/suivi-comptable.md
      - Mise en pratique: utilisateur/gestion-ventes/mise-en-pratique.md
    - Gestion des achats:
      - Demande d'achats: utilisateur/gestion-achats/demande.md
      - Commandes d'achats: utilisateur/gestion-achats/commande.md
      - Réceptions: utilisateur/gestion-achats/receptions.md
      - Factures d'achats: utilisateur/gestion-achats/factures.md
      - Fournisseurs: utilisateur/gestion-achats/fournisseurs.md
    - Gestion des stocks:
      - Articles: utilisateur/gestion-stocks/articles.md
      - Ajustements: utilisateur/gestion-stocks/ajustements.md
      - Inventaires: utilisateur/gestion-stocks/inventaires.md
      - Transferts intradépôt: utilisateur/gestion-stocks/transferts.md
      - Mise en pratique: utilisateur/gestion-stocks/mise-en-pratique.md
    - Mise en pratique: utilisateur/mise-en-pratique.md
  - Contact: contact.md
  - Terms: terms.md


theme:
  name: material                  # mkdocs,readthedocs
  custom_dir: overrides
  user_color_mode_toggle: true
  highlight.js: true
  shortcuts:
    help: 191    # ?
    next: 78     # n
    previous: 80 # p
    search: 83   # s
  features:                       # navbar lateral pour la navigation.
    - navigation.sections
  #   - navigation.tabs
  #   - navigation.instant
  #   - navigation.top

extra:
  version: 1.0.0
  copyright: NEXT

# extra_css:
#   - css/custom.css
