site_name: Manuel NEXT
site_author: Alex Lamizana
site_description: Documentation pour NEXT

nav:
  - Accueil: index.md
  - Introduction: introduction.md
  - Vue d'ensemble:
      - Architecture: Architecture.md
      - Principaux modules: principaux-modules.md
  - Guide utilisateur:
      - Connexion: utilisateur/connexion.md
      - Navigation: utilisateur/navigation.md
      - Gestion des clients: utilisateur/gestion-clients.md
      - Gestion des stocks: utilisateur/gestion-stocks.md
      - Gestion des fournisseurs: utilisateur/gestion-fournisseurs.md
      - Ressources Humaine: utilisateur/ressources-humaine.md
      - Mise en pratique: utilisateur/mise-en-pratique.md
  - Contact: contact.md
  - Terms: terms.md

theme:
  name: mkdocs #readthedocs 
  user_color_mode_toggle: true
  highlight.js: true
  shortcuts:
    help: 191    # ?
    next: 78     # n
    previous: 80 # p
    search: 83   # s

extra:
  version: 1.0.0
  copyright: NEXT

markdown_extensions:
  - toc:
      permalink: "#"